name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  DOCKER_IMAGE: booritas/slideio-manylinux2014
  DOCKER_IMAGE_TAG: v3.0.0
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub Registry
      run: docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      working-directory: ./docker
      run: docker build . --build-arg CONAN_REMOTE=${{ secrets.CONAN_REMOTE }} --build-arg CONAN_USER=${{ secrets.CONAN_USER }} --build-arg CONAN_PASSWORD=${{ secrets.CONAN_PASSWORD }} --file Dockerfile --tag $DOCKER_IMAGE:$DOCKER_IMAGE_TAG
    - name: Tag the latest image
      run: docker tag $DOCKER_IMAGE:$DOCKER_IMAGE_TAG $DOCKER_IMAGE:latest
    - name: Push the latest Docker image
      run: docker push $DOCKER_IMAGE:$DOCKER_IMAGE_TAG
    - name: Push the latest Docker image
      run: docker push $DOCKER_IMAGE:latest
